remote_theme: pmarsceill/just-the-docs
title: Ethereum Cheatsheet
description: Ethereum cheatsheet
url: "daniel.ai" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ethereum-cheatsheet"
plugins:
  - jemoji
