remote_theme: pmarsceill/just-the-docs
title: Daniel's Notes
description: Daniel's notes
# url: "daniel.ai" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/ethereum-cheatsheet"
plugins:
  - jemoji
